version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongo:27017/"
      MONGODB_DB: "users_test"
      JWT_SECRET: "secretwords"
      JWT_EXPIRES: "90d"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
